// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  activityId: __t.u64().primaryKey().name("activity_id"),
  tripId: __t.u64().name("trip_id"),
  name: __t.string(),
  description: __t.option(__t.string()),
  locationName: __t.option(__t.string()).name("location_name"),
  address: __t.option(__t.string()),
  lat: __t.option(__t.f64()),
  lng: __t.option(__t.f64()),
  locationProvider: __t.option(__t.string()).name("location_provider"),
  providerPlaceId: __t.option(__t.string()).name("provider_place_id"),
  externalUrl: __t.option(__t.string()).name("external_url"),
  date: __t.option(__t.string()),
  timeType: __t.string().name("time_type"),
  time: __t.option(__t.string()),
  order: __t.option(__t.i32()),
  createdBy: __t.identity().name("created_by"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
  deletedAt: __t.option(__t.timestamp()).name("deleted_at"),
});
