// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Activities = __t.object("Activities", {
  activityId: __t.u64(),
  tripId: __t.u64(),
  name: __t.string(),
  description: __t.option(__t.string()),
  locationName: __t.option(__t.string()),
  address: __t.option(__t.string()),
  lat: __t.option(__t.f64()),
  lng: __t.option(__t.f64()),
  locationProvider: __t.option(__t.string()),
  providerPlaceId: __t.option(__t.string()),
  externalUrl: __t.option(__t.string()),
  date: __t.option(__t.string()),
  timeType: __t.string(),
  time: __t.option(__t.string()),
  order: __t.option(__t.i32()),
  createdBy: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
});
export type Activities = __Infer<typeof Activities>;

export const ActivityLabels = __t.object("ActivityLabels", {
  activityLabelId: __t.u64(),
  activityId: __t.u64(),
  labelId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type ActivityLabels = __Infer<typeof ActivityLabels>;

export const Labels = __t.object("Labels", {
  labelId: __t.u64(),
  tripId: __t.u64(),
  name: __t.string(),
  color: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Labels = __Infer<typeof Labels>;

export const TripMembers = __t.object("TripMembers", {
  membershipId: __t.u64(),
  tripId: __t.u64(),
  identity: __t.identity(),
  role: __t.string(),
  createdAt: __t.timestamp(),
});
export type TripMembers = __Infer<typeof TripMembers>;

export const Trips = __t.object("Trips", {
  tripId: __t.u64(),
  title: __t.string(),
  description: __t.option(__t.string()),
  ownerIdentity: __t.identity(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deletedAt: __t.option(__t.timestamp()),
});
export type Trips = __Infer<typeof Trips>;

export const Users = __t.object("Users", {
  identity: __t.identity(),
  authUserId: __t.string(),
  displayName: __t.string(),
  email: __t.option(__t.string()),
  imageUrl: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Users = __Infer<typeof Users>;

