// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.2.0 (commit eb11e2f5c41dce6979715ad407996270d61329f6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddActivityLabelReducer from "./add_activity_label_reducer";
import AddCommentReducer from "./add_comment_reducer";
import ClearMapPresenceReducer from "./clear_map_presence_reducer";
import ClearTypingIndicatorReducer from "./clear_typing_indicator_reducer";
import CreateActivityReducer from "./create_activity_reducer";
import CreateLabelReducer from "./create_label_reducer";
import CreateTripReducer from "./create_trip_reducer";
import DeleteLabelReducer from "./delete_label_reducer";
import EditCommentReducer from "./edit_comment_reducer";
import EnsureUserProfileReducer from "./ensure_user_profile_reducer";
import InviteMemberReducer from "./invite_member_reducer";
import RemoveActivityLabelReducer from "./remove_activity_label_reducer";
import ReorderActivityWithinDayReducer from "./reorder_activity_within_day_reducer";
import RevokeMemberReducer from "./revoke_member_reducer";
import SoftDeleteActivityReducer from "./soft_delete_activity_reducer";
import SoftDeleteCommentReducer from "./soft_delete_comment_reducer";
import UpdateActivityReducer from "./update_activity_reducer";
import UpdateLabelReducer from "./update_label_reducer";
import UpdateMemberRoleReducer from "./update_member_role_reducer";
import UpdateTripReducer from "./update_trip_reducer";
import UpsertMapPresenceReducer from "./upsert_map_presence_reducer";
import UpsertTypingIndicatorReducer from "./upsert_typing_indicator_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ActivitiesRow from "./activities_table";
import ActivityCommentsRow from "./activity_comments_table";
import ActivityHistoryRow from "./activity_history_table";
import ActivityLabelsRow from "./activity_labels_table";
import LabelsRow from "./labels_table";
import MapPresenceRow from "./map_presence_table";
import TripMembersRow from "./trip_members_table";
import TripsRow from "./trips_table";
import TypingIndicatorsRow from "./typing_indicators_table";
import UsersRow from "./users_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  activities: __table({
    name: 'activities',
    indexes: [
      { accessor: 'activityId', name: 'activities_activity_id_idx_btree', algorithm: 'btree', columns: [
        'activityId',
      ] },
      { accessor: 'activities_trip_id', name: 'activities_trip_id_idx_btree', algorithm: 'btree', columns: [
        'tripId',
      ] },
    ],
    constraints: [
      { name: 'activities_activity_id_key', constraint: 'unique', columns: ['activityId'] },
    ],
  }, ActivitiesRow),
  activityComments: __table({
    name: 'activity_comments',
    indexes: [
      { accessor: 'activity_comments_activity_id', name: 'activity_comments_activity_id_idx_btree', algorithm: 'btree', columns: [
        'activityId',
      ] },
      { accessor: 'commentId', name: 'activity_comments_comment_id_idx_btree', algorithm: 'btree', columns: [
        'commentId',
      ] },
      { accessor: 'activity_comments_parent_comment_id', name: 'activity_comments_parent_comment_id_idx_btree', algorithm: 'btree', columns: [
        'parentCommentId',
      ] },
    ],
    constraints: [
      { name: 'activity_comments_comment_id_key', constraint: 'unique', columns: ['commentId'] },
    ],
  }, ActivityCommentsRow),
  activityHistory: __table({
    name: 'activity_history',
    indexes: [
      { accessor: 'activity_history_activity_id', name: 'activity_history_activity_id_idx_btree', algorithm: 'btree', columns: [
        'activityId',
      ] },
      { accessor: 'historyId', name: 'activity_history_history_id_idx_btree', algorithm: 'btree', columns: [
        'historyId',
      ] },
    ],
    constraints: [
      { name: 'activity_history_history_id_key', constraint: 'unique', columns: ['historyId'] },
    ],
  }, ActivityHistoryRow),
  activityLabels: __table({
    name: 'activity_labels',
    indexes: [
      { accessor: 'activity_labels_activity_id', name: 'activity_labels_activity_id_idx_btree', algorithm: 'btree', columns: [
        'activityId',
      ] },
      { accessor: 'activityLabelId', name: 'activity_labels_activity_label_id_idx_btree', algorithm: 'btree', columns: [
        'activityLabelId',
      ] },
      { accessor: 'activity_labels_label_id', name: 'activity_labels_label_id_idx_btree', algorithm: 'btree', columns: [
        'labelId',
      ] },
    ],
    constraints: [
      { name: 'activity_labels_activity_label_id_key', constraint: 'unique', columns: ['activityLabelId'] },
    ],
  }, ActivityLabelsRow),
  labels: __table({
    name: 'labels',
    indexes: [
      { accessor: 'labelId', name: 'labels_label_id_idx_btree', algorithm: 'btree', columns: [
        'labelId',
      ] },
      { accessor: 'labels_trip_id', name: 'labels_trip_id_idx_btree', algorithm: 'btree', columns: [
        'tripId',
      ] },
    ],
    constraints: [
      { name: 'labels_label_id_key', constraint: 'unique', columns: ['labelId'] },
    ],
  }, LabelsRow),
  mapPresence: __table({
    name: 'map_presence',
    indexes: [
      { accessor: 'map_presence_connection_id', name: 'map_presence_connection_id_idx_btree', algorithm: 'btree', columns: [
        'connectionId',
      ] },
      { accessor: 'presenceId', name: 'map_presence_presence_id_idx_btree', algorithm: 'btree', columns: [
        'presenceId',
      ] },
      { accessor: 'map_presence_trip_id', name: 'map_presence_trip_id_idx_btree', algorithm: 'btree', columns: [
        'tripId',
      ] },
      { accessor: 'map_presence_user_identity', name: 'map_presence_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'map_presence_presence_id_key', constraint: 'unique', columns: ['presenceId'] },
    ],
  }, MapPresenceRow),
  tripMembers: __table({
    name: 'trip_members',
    indexes: [
      { accessor: 'trip_members_identity', name: 'trip_members_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'membershipId', name: 'trip_members_membership_id_idx_btree', algorithm: 'btree', columns: [
        'membershipId',
      ] },
      { accessor: 'trip_members_trip_id', name: 'trip_members_trip_id_idx_btree', algorithm: 'btree', columns: [
        'tripId',
      ] },
    ],
    constraints: [
      { name: 'trip_members_membership_id_key', constraint: 'unique', columns: ['membershipId'] },
    ],
  }, TripMembersRow),
  trips: __table({
    name: 'trips',
    indexes: [
      { accessor: 'trips_owner_identity', name: 'trips_owner_identity_idx_btree', algorithm: 'btree', columns: [
        'ownerIdentity',
      ] },
      { accessor: 'tripId', name: 'trips_trip_id_idx_btree', algorithm: 'btree', columns: [
        'tripId',
      ] },
    ],
    constraints: [
      { name: 'trips_trip_id_key', constraint: 'unique', columns: ['tripId'] },
    ],
  }, TripsRow),
  typingIndicators: __table({
    name: 'typing_indicators',
    indexes: [
      { accessor: 'indicatorId', name: 'typing_indicators_indicator_id_idx_btree', algorithm: 'btree', columns: [
        'indicatorId',
      ] },
      { accessor: 'typing_indicators_trip_id', name: 'typing_indicators_trip_id_idx_btree', algorithm: 'btree', columns: [
        'tripId',
      ] },
      { accessor: 'typing_indicators_user_identity', name: 'typing_indicators_user_identity_idx_btree', algorithm: 'btree', columns: [
        'userIdentity',
      ] },
    ],
    constraints: [
      { name: 'typing_indicators_indicator_id_key', constraint: 'unique', columns: ['indicatorId'] },
    ],
  }, TypingIndicatorsRow),
  users: __table({
    name: 'users',
    indexes: [
      { accessor: 'identity', name: 'users_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'users_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UsersRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_activity_label", AddActivityLabelReducer),
  __reducerSchema("add_comment", AddCommentReducer),
  __reducerSchema("clear_map_presence", ClearMapPresenceReducer),
  __reducerSchema("clear_typing_indicator", ClearTypingIndicatorReducer),
  __reducerSchema("create_activity", CreateActivityReducer),
  __reducerSchema("create_label", CreateLabelReducer),
  __reducerSchema("create_trip", CreateTripReducer),
  __reducerSchema("delete_label", DeleteLabelReducer),
  __reducerSchema("edit_comment", EditCommentReducer),
  __reducerSchema("ensure_user_profile", EnsureUserProfileReducer),
  __reducerSchema("invite_member", InviteMemberReducer),
  __reducerSchema("remove_activity_label", RemoveActivityLabelReducer),
  __reducerSchema("reorder_activity_within_day", ReorderActivityWithinDayReducer),
  __reducerSchema("revoke_member", RevokeMemberReducer),
  __reducerSchema("soft_delete_activity", SoftDeleteActivityReducer),
  __reducerSchema("soft_delete_comment", SoftDeleteCommentReducer),
  __reducerSchema("update_activity", UpdateActivityReducer),
  __reducerSchema("update_label", UpdateLabelReducer),
  __reducerSchema("update_member_role", UpdateMemberRoleReducer),
  __reducerSchema("update_trip", UpdateTripReducer),
  __reducerSchema("upsert_map_presence", UpsertMapPresenceReducer),
  __reducerSchema("upsert_typing_indicator", UpsertTypingIndicatorReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.2.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

