// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  indicatorId: __t.u64().primaryKey().name("indicator_id"),
  connectionId: __t.connectionId().name("connection_id"),
  tripId: __t.u64().name("trip_id"),
  userIdentity: __t.identity().name("user_identity"),
  targetType: __t.string().name("target_type"),
  targetId: __t.string().name("target_id"),
  updatedAt: __t.timestamp().name("updated_at"),
});
