// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  activityId: __t.u64(),
  name: __t.string(),
  description: __t.option(__t.string()),
  date: __t.option(__t.string()),
  timeType: __t.string(),
  time: __t.option(__t.string()),
  order: __t.option(__t.i32()),
  locationName: __t.option(__t.string()),
  address: __t.option(__t.string()),
  lat: __t.option(__t.f64()),
  lng: __t.option(__t.f64()),
  locationProvider: __t.option(__t.string()),
  providerPlaceId: __t.option(__t.string()),
  externalUrl: __t.option(__t.string()),
};
